### PR TITLE
Cleaning Code - Initial

### PR DESCRIPTION
**Pull request by ehamamrah**
Just did a small cleaning for the code, Code quality needs a lot of improvements and will be working on it next.

### CODE REVIEW

**Comment by ehamamrah** [comment]
@AliOsm

**Comment by AliOsm** [comment]
I apologize for the late response but I could not connect to the internet, I checked the code and I fixed some errors, your changes are great, thank you, I will merge them now as I wait for more.

**Comment by ehamamrah** [comment]
No worries bro and wait for more i will do my best to support you.
I dropped you an email, please check it and send me ur phone number.

**Comment by AliOsm** [comment]
Done.

**Pull request merged**
